# Generated by Django 4.2.2 on 2023-07-04 07:58

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='src',
            field=models.ImageField(default='app_users/avatars/default.png', upload_to=myauth.models.avatar_directory_path, verbose_name='Ссылка'),
        ),
    ]
