# Generated by Django 4.2.2 on 2023-07-04 09:00

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_alter_avatar_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='src',
            field=models.ImageField(upload_to=myauth.models.avatar_directory_path, verbose_name='Ссылка'),
        ),
    ]
