# Generated by Django 4.2.2 on 2023-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_remove_profile_email_alter_avatar_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=230, null=True),
        ),
    ]
