# Generated by Django 4.2.2 on 2023-07-04 11:39

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
