# Generated by Django 4.2.3 on 2023-07-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
