# Generated by Django 4.2.3 on 2023-07-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_specification_product_specifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Спецификация', 'verbose_name_plural': 'Спецификации'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
