# Generated by Django 4.2.3 on 2023-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_reviews_review_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, null=True, to='products.category', verbose_name='Подкатегории'),
        ),
    ]
