# Generated by Django 4.2.3 on 2023-07-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='products.review', verbose_name='Отзывы'),
        ),
    ]
