# Generated by Django 4.2.3 on 2023-07-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default=123123123, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
